# Generated by Django 4.1.2 on 2022-11-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='img1',
            field=models.ImageField(upload_to='image1/'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='image2/'),
        ),
    ]
